#ifndef MTP_H
#define MTP_H

#include <cstdint>

constexpr std::uint32_t MTP_PARENT_ROOT          = 0xFFFFFFFF;
constexpr std::uint32_t INVALID_OBJECT_HANDLE    = 0xFFFFFFFF;

//Container Types
constexpr std::uint16_t MTP_CONTAINER_TYPE_UNDEFINED    = 0x0000;
constexpr std::uint16_t MTP_CONTAINER_TYPE_COMMAND      = 0x0001;
constexpr std::uint16_t MTP_CONTAINER_TYPE_DATA         = 0x0002;
constexpr std::uint16_t MTP_CONTAINER_TYPE_RESPONSE     = 0x0003;
constexpr std::uint16_t MTP_CONTAINER_TYPE_EVENT        = 0x0004;

//Container offsets
constexpr int MTP_CONTAINER_LENGTH_OFFSET           = 0;
constexpr int MTP_CONTAINER_TYPE_OFFSET             = 4;
constexpr int MTP_CONTAINER_CODE_OFFSET             = 6;
constexpr int MTP_CONTAINER_TRANSACTION_ID_OFFSET   = 8;
constexpr int MTP_CONTAINER_PARAMETER_OFFSET        = 12;
constexpr int MTP_CONTAINER_HEADER_SIZE             = 12;

//MTP data types codes
constexpr std::uint16_t MTP_DATA_TYPE_UNDEF     = 0x0000; //Undefined
constexpr std::uint16_t MTP_DATA_TYPE_INT8      = 0x0001; //Signed 8-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_UINT8     = 0x0002; //Unsigned 8-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_INT16     = 0x0003; //Signed 16-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_UINT16    = 0x0004; //Unsigned 16-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_INT32     = 0x0005; //Signed 32-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_UINT32    = 0x0006; //Unsigned 32-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_INT64     = 0x0007; //Signed 64-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_UINT64    = 0x0008; //Unsigned 64-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_INT128    = 0x0009; //Signed 128-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_UINT128   = 0x000A; //Unsigned 128-bit integer
constexpr std::uint16_t MTP_DATA_TYPE_AINT8     = 0x4001; //Array of signed 8-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AUINT8    = 0x4002; //Array of unsigned 8-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AINT16    = 0x4003; //Array of signed 16-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AUINT16   = 0x4004; //Array of unsigned 16-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AINT32    = 0x4005; //Array of signed 32-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AUINT32   = 0x4006; //Array of unsigned 32-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AINT64    = 0x4007; //Array of signed 64-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AUINT64   = 0x4008; //Array of unsigned 64-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AINT128   = 0x4009; //Array of signed 128-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_AUINT128  = 0x400A; //Array of unsigned 128-bit integers
constexpr std::uint16_t MTP_DATA_TYPE_STR       = 0xFFFF; //Variable-length Unicode string

//MTP object format codes
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_0                       = 0x3000; //Undefined object
constexpr std::uint16_t MTP_OBJECT_FORMAT_ASSOCIATION                       = 0x3001; //Association (for example, a folder)
constexpr std::uint16_t MTP_OBJECT_FORMAT_SCRIPT                            = 0x3002; //Device model-specific script
constexpr std::uint16_t MTP_OBJECT_FORMAT_EXECUTABLE                        = 0x3003; //Device model-specific binary executable
constexpr std::uint16_t MTP_OBJECT_FORMAT_TEXT                              = 0x3004; //Text file
constexpr std::uint16_t MTP_OBJECT_FORMAT_HTML                              = 0x3005; //Hypertext Markup Language file (text)
constexpr std::uint16_t MTP_OBJECT_FORMAT_DPOF                              = 0x3006; //Digital Print Order Format file (text)
constexpr std::uint16_t MTP_OBJECT_FORMAT_AIFF                              = 0x3007; //Audio clip
constexpr std::uint16_t MTP_OBJECT_FORMAT_WAV                               = 0x3008; //Audio clip
constexpr std::uint16_t MTP_OBJECT_FORMAT_MP3                               = 0x3009; //MPEG-1 Layer III audio (ISO/IEC 13818-3)
constexpr std::uint16_t MTP_OBJECT_FORMAT_AVI                               = 0x300A; //Video clip
constexpr std::uint16_t MTP_OBJECT_FORMAT_MPEG                              = 0x300B; //Video clip
constexpr std::uint16_t MTP_OBJECT_FORMAT_ASF                               = 0x300C; //Microsoft Advanced Streaming Format (video)
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_IMAGE                   = 0x3800; //Undefined image object
constexpr std::uint16_t MTP_OBJECT_FORMAT_EXIF_JPEG                         = 0x3801; //Exchangeable File Format, JEIDA standard
constexpr std::uint16_t MTP_OBJECT_FORMAT_TIFF_EP                           = 0x3802; //Tag Image File Format for Electronic Photography
constexpr std::uint16_t MTP_OBJECT_FORMAT_FLASHPIX                          = 0x3803; //Structured Storage Image Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_BMP                               = 0x3804; //Microsoft Windows Bitmap file
constexpr std::uint16_t MTP_OBJECT_FORMAT_CIFF                              = 0x3805; //Canon Camera Image File Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_1                       = 0x3806; //Reserved
constexpr std::uint16_t MTP_OBJECT_FORMAT_GIF                               = 0x3807; //Graphics Interchange Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_JFIF                              = 0x3808; //JPEG File Interchange Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_CD                                = 0x3809; //PhotoCD Image Pac
constexpr std::uint16_t MTP_OBJECT_FORMAT_PICT                              = 0x380A; //Quickdraw Image Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_PNG                               = 0x380B; //Portable Network Graphics
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_2                       = 0x380C; //Reserved
constexpr std::uint16_t MTP_OBJECT_FORMAT_TIFF                              = 0x380D; //Tag Image File Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_TIFF_IT                           = 0x380E; //Tag Image File Format for Information Technology (graphic arts)
constexpr std::uint16_t MTP_OBJECT_FORMAT_JP2                               = 0x380F; //JPEG2000 Baseline File Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_JPX                               = 0x3810; //JPEG2000 Extended File Format
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_FIRMWARE                = 0xB802;
constexpr std::uint16_t MTP_OBJECT_FORMAT_WINDOWS_IMAGE_FORMAT              = 0xB881;
constexpr std::uint16_t MTP_OBJECT_FORMAT_WBMP                              = 0xB803; //Wireless Application Protocol Bitmap Format (.wbmp) .image/vnd.wap.wbmp
constexpr std::uint16_t MTP_OBJECT_FORMAT_JPEG_XR                           = 0xB804; //JPEG XR, also known as HD Photo (.hdp, jxr, .wpd). image/vnd.ms-photo.ISO/IEC 29199-2:2009
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_AUDIO                   = 0xB900; //Undefined audio object
constexpr std::uint16_t MTP_OBJECT_FORMAT_WMA                               = 0xB901; //Windows Media Audio
constexpr std::uint16_t MTP_OBJECT_FORMAT_OGG                               = 0xB902;
constexpr std::uint16_t MTP_OBJECT_FORMAT_AAC                               = 0xB903; //Advanced Audio Coding (.aac). audio/aac. MPEG-4 AAC.
constexpr std::uint16_t MTP_OBJECT_FORMAT_AUDIBLE                           = 0xB904;
constexpr std::uint16_t MTP_OBJECT_FORMAT_FLAC                              = 0xB906; //Free Lossless Audio Codec
constexpr std::uint16_t MTP_OBJECT_FORMAT_QCELP                             = 0xB907; //Qualcomm Code Excited Linear Prediction (.qcp). audio/qcelp
constexpr std::uint16_t MTP_OBJECT_FORMAT_AMR                               = 0xB908; //Adaptive Multi-Rate audio codec (.amr). audio/amr
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_VIDEO                   = 0xB980; //Undefined video object
constexpr std::uint16_t MTP_OBJECT_FORMAT_WMV                               = 0xB981; //Windows Media Video
constexpr std::uint16_t MTP_OBJECT_FORMAT_MP4_CONTAINER                     = 0xB982; //ISO 14496-1
constexpr std::uint16_t MTP_OBJECT_FORMAT_MP2                               = 0xB983; //MPEG-1 Layer II audio (ISO/IEC 13818-3)
constexpr std::uint16_t MTP_OBJECT_FORMAT_3GP_CONTAINER                     = 0xB984; //3GPP file format. Details: http://www.3gpp.org/ftp/Specs/html-info/26244.htm (page title - “Transparent end-to-end packet switched streaming service, 3GPP file format”)
constexpr std::uint16_t MTP_OBJECT_FORMAT_3G2                               = 0xB985; //3GPP2 format (.3g2). video/3gpp2, audio/3gpp2
constexpr std::uint16_t MTP_OBJECT_FORMAT_AVCHD                             = 0xB986; //MPEG-4 AVC video and Dolby Digital audio within an MPEG-2 Transport Stream as constrained by the AVCHD format specification
constexpr std::uint16_t MTP_OBJECT_FORMAT_ATSC_TS                           = 0xB987; //MPEG-2 video and AC-3 audio within an ATSC-compliant MPEG-2 Transport Stream
constexpr std::uint16_t MTP_OBJECT_FORMAT_DVB_TS                            = 0xB988; //MPEG-2 video and MPEG-1 Layer II or AC-3 audio within a DVB-compliant MPEG-2 Transport Stream
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_COLLECTION              = 0xBA00;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_MULTIMEDIA_ALBUM         = 0xBA01;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_IMAGE_ALBUM              = 0xBA02;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_AUDIO_ALBUM              = 0xBA03;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_VIDEO_ALBUM              = 0xBA04;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_AUDIO_AND_VIDEO_PLAYLIST = 0xBA05;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_CONTACT_GROUP            = 0xBA06;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_MESSAGE_FOLDER           = 0xBA07;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_CHAPTERED_PRODUCTION     = 0xBA08;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_AUDIO_PLAYLIST           = 0xBA09;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_VIDEO_PLAYLIST           = 0xBA0A;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_MEDIACAST                = 0xBA0B; //For use with mediacasts references multimedia enclosures of RSS feeds or episodic content
constexpr std::uint16_t MTP_OBJECT_FORMAT_WPL_PLAYLIST                      = 0xBA10;
constexpr std::uint16_t MTP_OBJECT_FORMAT_M3U_PLAYLIST                      = 0xBA11;
constexpr std::uint16_t MTP_OBJECT_FORMAT_MPL_PLAYLIST                      = 0xBA12;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ASX_PLAYLIST                      = 0xBA13;
constexpr std::uint16_t MTP_OBJECT_FORMAT_PLS_PLAYLIST                      = 0xBA14;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_DOCUMENT                = 0xBA80;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_DOCUMENT                 = 0xBA81;
constexpr std::uint16_t MTP_OBJECT_FORMAT_XML_DOCUMENT                      = 0xBA82;
constexpr std::uint16_t MTP_OBJECT_FORMAT_MICROSOFT_WORD_DOCUMENT           = 0xBA83;
constexpr std::uint16_t MTP_OBJECT_FORMAT_MHT_COMPILED_HTML_DOCUMENT        = 0xBA84;
constexpr std::uint16_t MTP_OBJECT_FORMAT_MICROSOFT_EXCEL_SPREADSHEET       = 0xBA85;
constexpr std::uint16_t MTP_OBJECT_FORMAT_MICROSOFT_POWERPOINT_PRESENTATION = 0xBA86;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_MESSAGE                 = 0xBB00;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_MESSAGE                  = 0xBB01;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_BOOKMARK                = 0xBB10;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_BOOKMARK                 = 0xBB11;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_APPOINTMENT             = 0xBB20;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_APPOINTMENT              = 0xBB21;
constexpr std::uint16_t MTP_OBJECT_FORMAT_VCALENDAR                         = 0xBB22;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_TASK                    = 0xBB40;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_TASK                     = 0xBB41;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ICALENDAR                         = 0xBB42;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_NOTE                    = 0xBB60;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_NOTE                     = 0xBB61;
constexpr std::uint16_t MTP_OBJECT_FORMAT_UNDEFINED_CONTACT                 = 0xBB80;
constexpr std::uint16_t MTP_OBJECT_FORMAT_ABSTRACT_CONTACT                  = 0xBB81;
constexpr std::uint16_t MTP_OBJECT_FORMAT_VCARD_2                           = 0xBB82;
constexpr std::uint16_t MTP_OBJECT_FORMAT_VCARD_3                           = 0xBB83;

//MTP Object Property Codes
constexpr std::uint16_t MTP_OBJECT_PROPERTY_STORAGE_ID =                            0xDC01;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_OBJECT_FORMAT =                         0xDC02;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PROTECTION_STATUS =                     0xDC03;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_OBJECT_SIZE =                           0xDC04;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ASSOCIATION_TYPE =                      0xDC05;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ASSOCIATION_DESC =                      0xDC06;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_OBJECT_FILE_NAME =                      0xDC07;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DATE_CREATED =                          0xDC08;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DATE_MODIFIED =                         0xDC09;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_KEYWORDS =                              0xDC0A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PARENT_OBJECT =                         0xDC0B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ALLOWED_FOLDER_CONTENTS =               0xDC0C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_HIDDEN =                                0xDC0D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SYSTEM_OBJECT =                         0xDC0E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PERSISTENT_UNIQUE_OBJECT_IDENTIFIER =   0xDC41;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SYNC_ID =                               0xDC42;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PROPERTY_BAG =                          0xDC43;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_NAME =                                  0xDC44;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_CREATED_BY =                            0xDC45;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ARTIST =                                0xDC46;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DATE_AUTHORED =                         0xDC47;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DESCRIPTION =                           0xDC48;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_URL_REFERENCE =                         0xDC49;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_LANGUAGE_LOCALE =                       0xDC4A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_COPYRIGHT_INFORMATION =                 0xDC4B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SOURCE =                                0xDC4C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ORIGIN_LOCATION =                       0xDC4D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DATE_ADDED =                            0xDC4E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_NON_CONSUMABLE =                        0xDC4F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_CORRUPT_UNPLAYABLE =                    0xDC50;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PRODUCER_SERIAL_NUMBER =                0xDC51;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_FORMAT =          0xDC81;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_SIZE =            0xDC82;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_HEIGHT =          0xDC83;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_WIDTH =           0xDC84;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_DURATION =        0xDC85;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_REPRESENTATIVE_SAMPLE_DATA =            0xDC86;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_WIDTH =                                 0xDC87;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_HEIGHT =                                0xDC88;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DURATION =                              0xDC89;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_RATING =                                0xDC8A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_TRACK =                                 0xDC8B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_GENRE =                                 0xDC8C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_CREDITS =                               0xDC8D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_LYRICS =                                0xDC8E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SUBSCRIPTION_CONTENT_ID =               0xDC8F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PRODUCED_BY =                           0xDC90;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_USE_COUNT =                             0xDC91;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SKIP_COUNT =                            0xDC92;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_LAST_ACCESSED =                         0xDC93;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PARENTAL_RATING =                       0xDC94;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_META_GENRE =                            0xDC95;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_COMPOSER =                              0xDC96;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EFFECTIVE_RATING =                      0xDC97;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SUBTITLE =                              0xDC98;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ORIGINAL_RELEASE_DATE =                 0xDC99;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ALBUM_NAME =                            0xDC9A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ALBUM_ARTIST =                          0xDC9B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MOOD =                                  0xDC9C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DRM_STATUS =                            0xDC9D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SUB_DESCRIPTION =                       0xDC9E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_IS_CROPPED =                            0xDCD1;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_IS_COLOUR_CORRECTED =                   0xDCD2;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_IMAGE_BIT_DEPTH =                       0xDCD3;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_F_NUMBER =                              0xDCD4;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EXPOSURE_TIME =                         0xDCD5;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EXPOSURE_INDEX =                        0xDCD6;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_TOTAL_BITRATE =                         0xDE91;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BITRATE_TYPE =                          0xDE92;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SAMPLE_RATE =                           0xDE93;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_NUMBER_OF_CHANNELS =                    0xDE94;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_AUDIO_BIT_DEPTH =                       0xDE95;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SCAN_TYPE =                             0xDE97;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_AUDIO_WAVE_CODEC =                      0xDE99;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_AUDIO_BITRATE =                         0xDE9A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_VIDEO_FOURCC_CODEC =                    0xDE9B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_VIDEO_BITRATE =                         0xDE9C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_FRAMES_PER_THOUSAND_SECONDS =           0xDE9D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_KEYFRAME_DISTANCE =                     0xDE9E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BUFFER_SIZE =                           0xDE9F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ENCODING_QUALITY =                      0xDEA0;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ENCODING_PROFILE =                      0xDEA1;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_DISPLAY_NAME =                          0xDCE0;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BODY_TEXT =                             0xDCE1;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SUBJECT =                               0xDCE2;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PRIORITY =                              0xDCE3;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_GIVEN_NAME =                            0xDD00;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MIDDLE_NAMES =                          0xDD01;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_FAMILY_NAME =                           0xDD02;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PREFIX =                                0xDD03;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_SUFFIX =                                0xDD04;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONETIC_GIVEN_NAME =                   0xDD05;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONETIC_FAMILY_NAME =                  0xDD06;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_PRIMARY =                         0xDD07;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_PERSONAL_1 =                      0xDD08;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_PERSONAL_2 =                      0xDD09;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_BUSINESS_1 =                      0xDD0A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_BUSINESS_2 =                      0xDD0B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EMAIL_OTHERS =                          0xDD0C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_PRIMARY =                  0xDD0D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_PERSONAL =                 0xDD0E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_PERSONAL_2 =               0xDD0F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_BUSINESS =                 0xDD10;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_BUSINESS_2 =               0xDD11;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_MOBILE =                   0xDD12;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_MOBILE_2 =                 0xDD13;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_FAX_NUMBER_PRIMARY =                    0xDD14;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_FAX_NUMBER_PERSONAL =                   0xDD15;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_FAX_NUMBER_BUSINESS =                   0xDD16;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PAGER_NUMBER =                          0xDD17;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONE_NUMBER_OTHERS =                   0xDD18;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PRIMARY_WEB_ADDRESS =                   0xDD19;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PERSONAL_WEB_ADDRESS =                  0xDD1A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BUSINESS_WEB_ADDRESS =                  0xDD1B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_INSTANT_MESSENGER_ADDRESS =             0xDD1C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_INSTANT_MESSENGER_ADDRESS_2 =           0xDD1D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_INSTANT_MESSENGER_ADDRESS_3 =           0xDD1E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_FULL =          0xDD1F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_LINE_1 =        0xDD20;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_LINE_2 =        0xDD21;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_CITY =          0xDD22;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_REGION =        0xDD23;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_POSTAL_CODE =   0xDD24;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_PERSONAL_COUNTRY =       0xDD25;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_FULL =          0xDD26;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_LINE_1 =        0xDD27;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_LINE_2 =        0xDD28;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_CITY =          0xDD29;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_REGION =        0xDD2A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_POSTAL_CODE =   0xDD2B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_BUSINESS_COUNTRY =       0xDD2C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_FULL =             0xDD2D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_LINE_1 =           0xDD2E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_LINE_2 =           0xDD2F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_CITY =             0xDD30;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_REGION =           0xDD31;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_POSTAL_CODE =      0xDD32;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_POSTAL_ADDRESS_OTHER_COUNTRY =          0xDD33;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ORGANIZATION_NAME =                     0xDD34;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_PHONETIC_ORGANIZATION_NAME =            0xDD35;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ROLE =                                  0xDD36;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BIRTHDATE =                             0xDD37;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_TO =                            0xDD40;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_CC =                            0xDD41;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_BCC =                           0xDD42;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_READ =                          0xDD43;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_RECEIVED_TIME =                 0xDD44;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MESSAGE_SENDER =                        0xDD45;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_BEGIN_TIME =                   0xDD50;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_END_TIME =                     0xDD51;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_LOCATION =                     0xDD52;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_REQUIRED_ATTENDEES =           0xDD54;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_OPTIONAL_ATTENDEES =           0xDD55;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_RESOURCES =                    0xDD56;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_ACCEPTED =                     0xDD57;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_TENTATIVE =                    0xDD58;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_DECLINED =                     0xDD59;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_REMINDER_TIME =                0xDD5A;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_OWNER =                        0xDD5B;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_ACTIVITY_STATUS =                       0xDD5C;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_OWNER =                                 0xDD5D;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_EDITOR =                                0xDD5E;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_WEBMASTER =                             0xDD5F;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_URL_SOURCE =                            0xDD60;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_URL_DESTINATION =                       0xDD61;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_TIME_BOOKMARK =                         0xDD62;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_OBJECT_BOOKMARK =                       0xDD63;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_BYTE_BOOKMARK =                         0xDD64;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_LAST_BUILD_DATE =                       0xDD70;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_TIME_TO_LIVE =                          0xDD71;
constexpr std::uint16_t MTP_OBJECT_PROPERTY_MEDIA_GUID =                            0xDD72;

//MTP Device Property Codes
constexpr std::uint16_t MTP_DEVICE_PROPERTY_UNDEFINED = 0x5000;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_BATTERY_LEVEL = 0x5001;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FUNCTIONAL_MODE = 0x5002;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_IMAGE_SIZE = 0x5003;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_COMPRESSION_SETTING = 0x5004;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_WHITE_BALANCE = 0x5005;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_RGB_GAIN = 0x5006;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_F_NUMBER = 0x5007;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FOCAL_LENGTH = 0x5008;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FOCUS_DISTANCE = 0x5009;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FOCUS_MODE = 0x500A;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EXPOSURE_METERING_MODE = 0x500B;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FLASH_MODE = 0x500C;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EXPOSURE_TIME = 0x500D;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EXPOSURE_PROGRAM_MODE = 0x500E;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EXPOSURE_INDEX = 0x500F;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EXPOSURE_BIAS_COMPENSATION = 0x5010;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_DATETIME = 0x5011;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_CAPTURE_DELAY = 0x5012;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_STILL_CAPTURE_MODE = 0x5013;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_CONTRAST = 0x5014;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_SHARPNESS = 0x5015;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_DIGITAL_ZOOM = 0x5016;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_EFFECT_MODE = 0x5017;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_BURST_NUMBER = 0x5018;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_BURST_INTERVAL = 0x5019;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_TIMELAPSE_NUMBER = 0x501A;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_TIMELAPSE_INTERVAL = 0x501B;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_FOCUS_METERING_MODE = 0x501C;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_UPLOAD_URL = 0x501D;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_ARTIST = 0x501E;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_COPYRIGHT_INFO = 0x501F;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_SYNCHRONIZATION_PARTNER = 0xD401;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_DEVICE_FRIENDLY_NAME = 0xD402;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_VOLUME = 0xD403;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_SUPPORTED_FORMATS_ORDERED = 0xD404;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_DEVICE_ICON = 0xD405;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_PLAYBACK_RATE = 0xD410;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_PLAYBACK_OBJECT = 0xD411;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_PLAYBACK_CONTAINER_INDEX = 0xD412;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_SESSION_INITIATOR_VERSION_INFO = 0xD406;
constexpr std::uint16_t MTP_DEVICE_PROPERTY_PERCEIVED_DEVICE_TYPE = 0xD407;

// MTP Operation Codes
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETDEVICEINFO = 0x1001;
constexpr std::uint16_t MTP_DEVICE_OPERATION_OPENSESSION = 0x1002;
constexpr std::uint16_t MTP_DEVICE_OPERATION_CLOSESESSION = 0x1003;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETSTORAGEIDS = 0x1004;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETSTORAGEINFO = 0x1005;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETNUMOBJECTS = 0x1006;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTHANDLES = 0x1007;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTINFO = 0x1008;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECT = 0x1009;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETTHUMB = 0x100A;
constexpr std::uint16_t MTP_DEVICE_OPERATION_DELETEOBJECT = 0x100B;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SENDOBJECTINFO = 0x100C;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SENDOBJECT = 0x100D;
constexpr std::uint16_t MTP_DEVICE_OPERATION_INITIATECAPTURE = 0x100E;
constexpr std::uint16_t MTP_DEVICE_OPERATION_FORMATSTORE = 0x100F;
constexpr std::uint16_t MTP_DEVICE_OPERATION_RESETDEVICE = 0x1010;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SELFTEST = 0x1011;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SETOBJECTPROTECTION = 0x1012;
constexpr std::uint16_t MTP_DEVICE_OPERATION_POWERDOWN = 0x1013;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETDEVICEPROPDESC = 0x1014;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETDEVICEPROPVALUE = 0x1015;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SETDEVICEPROPVALUE = 0x1016;
constexpr std::uint16_t MTP_DEVICE_OPERATION_RESETDEVICEPROPVALUE = 0x1017;
constexpr std::uint16_t MTP_DEVICE_OPERATION_TERMINATEOPENCAPTURE = 0x1018;
constexpr std::uint16_t MTP_DEVICE_OPERATION_MOVEOBJECT = 0x1019;
constexpr std::uint16_t MTP_DEVICE_OPERATION_COPYOBJECT = 0x101A;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETPARTIALOBJECT = 0x101B;
constexpr std::uint16_t MTP_DEVICE_OPERATION_INITIATEOPENCAPTURE = 0x101C;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTPROPSSUPPORTED = 0x9801;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTPROPDESC = 0x9802;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTPROPVALUE = 0x9803;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SETOBJECTPROPVALUE = 0x9804;
constexpr std::uint16_t MTP_DEVICE_OPERATION_GETOBJECTREFERENCES = 0x9810;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SETOBJECTREFERENCES = 0x9811;
constexpr std::uint16_t MTP_DEVICE_OPERATION_SKIP = 0x9820;

//MTP Event Codes
constexpr std::uint16_t MTP_EVENT_UNDEFINED = 0x4000;
constexpr std::uint16_t MTP_EVENT_CANCELTRANSACTION = 0x4001;
constexpr std::uint16_t MTP_EVENT_OBJECTADDED = 0x4002;
constexpr std::uint16_t MTP_EVENT_OBJECTREMOVED = 0x4003;
constexpr std::uint16_t MTP_EVENT_STOREADDED = 0x4004;
constexpr std::uint16_t MTP_EVENT_STOREREMOVED = 0x4005;
constexpr std::uint16_t MTP_EVENT_DEVICEPROPCHANGED = 0x4006;
constexpr std::uint16_t MTP_EVENT_OBJECTINFOCHANGED = 0x4007;
constexpr std::uint16_t MTP_EVENT_DEVICEINFOCHANGED = 0x4008;
constexpr std::uint16_t MTP_EVENT_REQUESTOBJECTTRANSFER = 0x4009;
constexpr std::uint16_t MTP_EVENT_STOREFULL = 0x400A;
constexpr std::uint16_t MTP_EVENT_DEVICERESET = 0x400B;
constexpr std::uint16_t MTP_EVENT_STORAGEINFOCHANGED = 0x400C;
constexpr std::uint16_t MTP_EVENT_CAPTURECOMPLETE = 0x400D;
constexpr std::uint16_t MTP_EVENT_UNREPORTEDSTATUS = 0x400E;
constexpr std::uint16_t MTP_EVENT_OBJECTPROPCHANGED = 0xC801;
constexpr std::uint16_t MTP_EVENT_OBJECTPROPDESCCHANGED = 0xC802;
constexpr std::uint16_t MTP_EVENT_OBJECTREFERENCESCHANGED = 0xC803;

//MTP Response Codes
constexpr std::uint16_t MTP_RESPONSE_UNDEFINED = 0x2000;
constexpr std::uint16_t MTP_RESPONSE_OK = 0x2001;
constexpr std::uint16_t MTP_RESPONSE_GENERAL_ERROR = 0x2002;
constexpr std::uint16_t MTP_RESPONSE_SESSION_NOT_OPEN = 0x2003;
constexpr std::uint16_t MTP_RESPONSE_INVALID_TRANSACTIONID = 0x2004;
constexpr std::uint16_t MTP_RESPONSE_OPERATION_NOT_SUPPORTED = 0x2005;
constexpr std::uint16_t MTP_RESPONSE_PARAMETER_NOT_SUPPORTED = 0x2006;
constexpr std::uint16_t MTP_RESPONSE_INCOMPLETE_TRANSFER = 0x2007;
constexpr std::uint16_t MTP_RESPONSE_INVALID_STORAGEID = 0x2008;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECT_HANDLE = 0x2009;
constexpr std::uint16_t MTP_RESPONSE_DEVICEPROP_NOT_SUPPORTED = 0x200A;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECTFORMATCODE = 0x200B;
constexpr std::uint16_t MTP_RESPONSE_STORE_FULL = 0x200C;
constexpr std::uint16_t MTP_RESPONSE_OBJECT_WRITEPROTECTED = 0x200D;
constexpr std::uint16_t MTP_RESPONSE_STORE_READ_ONLY = 0x200E;
constexpr std::uint16_t MTP_RESPONSE_ACCESS_DENIED = 0x200F;
constexpr std::uint16_t MTP_RESPONSE_NO_THUMBNAIL_PRESENT = 0x2010;
constexpr std::uint16_t MTP_RESPONSE_SELFTEST_FAILED = 0x2011;
constexpr std::uint16_t MTP_RESPONSE_PARTIAL_DELETION = 0x2012;
constexpr std::uint16_t MTP_RESPONSE_STORE_NOT_AVAILABLE = 0x2013;
constexpr std::uint16_t MTP_RESPONSE_SPECIFICATION_BY_FORMAT_UNSUPPORTED = 0x2014;
constexpr std::uint16_t MTP_RESPONSE_NO_VALID_OBJECTINFO = 0x2015;
constexpr std::uint16_t MTP_RESPONSE_INVALID_CODE_FORMAT = 0x2016;
constexpr std::uint16_t MTP_RESPONSE_UNKNOWN_VENDOR_CODE = 0x2017;
constexpr std::uint16_t MTP_RESPONSE_CAPTURE_ALREADY_TERMINATED = 0x2018;
constexpr std::uint16_t MTP_RESPONSE_DEVICE_BUSY = 0x2019;
constexpr std::uint16_t MTP_RESPONSE_INVALID_PARENTOBJECT = 0x201A;
constexpr std::uint16_t MTP_RESPONSE_INVALID_DEVICEPROP_FORMAT = 0x201B;
constexpr std::uint16_t MTP_RESPONSE_INVALID_DEVICEPROP_VALUE = 0x201C;
constexpr std::uint16_t MTP_RESPONSE_INVALID_PARAMETER = 0x201D;
constexpr std::uint16_t MTP_RESPONSE_SESSION_ALREADY_OPEN = 0x201E;
constexpr std::uint16_t MTP_RESPONSE_TRANSACTION_CANCELLED = 0x201F;
constexpr std::uint16_t MTP_RESPONSE_SPECIFICATION_OF_DESTINATION_UNSUPPORTED = 0x2020;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECTPROPCODE = 0xA801;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECTPROP_FORMAT = 0xA802;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECTPROP_VALUE = 0xA803;
constexpr std::uint16_t MTP_RESPONSE_INVALID_OBJECTREFERENCE = 0xA804;
constexpr std::uint16_t MTP_RESPONSE_GROUP_NOT_SUPPORTED = 0xA805;
constexpr std::uint16_t MTP_RESPONSE_INVALID_DATASET = 0xA806;
constexpr std::uint16_t MTP_RESPONSE_SPECIFICATION_BY_GROUP_UNSUPPORTED = 0xA807;
constexpr std::uint16_t MTP_RESPONSE_SPECIFICATION_BY_DEPTH_UNSUPPORTED = 0xA808;
constexpr std::uint16_t MTP_RESPONSE_OBJECT_TOO_LARGE = 0xA809;
constexpr std::uint16_t MTP_RESPONSE_OBJECTPROP_NOT_SUPPORTED = 0xA80A;

//MTP storage types
constexpr std::uint16_t  MTP_STORAGE_TYPE_UNDEFINED = 0x0000;
constexpr std::uint16_t  MTP_STORAGE_TYPE_FIXED_ROM = 0x0001;
constexpr std::uint16_t  MTP_STORAGE_TYPE_REMOVABLE_ROM = 0x0002;
constexpr std::uint16_t  MTP_STORAGE_TYPE_FIXED_RAM = 0x0003;
constexpr std::uint16_t  MTP_STORAGE_TYPE_REMOVABLE_RAM = 0x0004;

//MTP Storage File System
constexpr std::uint16_t MTP_SOTRAGE_FILESYSTEM_UNDEFINED = 0x0000;
constexpr std::uint16_t MTP_SOTRAGE_FILESYSTEM_GENERIC_FLAT = 0x0001;
constexpr std::uint16_t MTP_SOTRAGE_FILESYSTEM_GENERIC_HIERARCHICAL = 0x0002;
constexpr std::uint16_t MTP_SOTRAGE_FILESYSTEM_DCF = 0x0003;

//MTP Access Capability
constexpr std::uint16_t MTP_ACCESS_CAPABILITY_READ_WRITE = 0x0000;
constexpr std::uint16_t MTP_ACCESS_CAPABILITY_READ_ONLY_WITHOUT_OBJECT_DELETION = 0x0001;
constexpr std::uint16_t MTP_ACCESS_CAPABILITY_READ_ONLY_WITH_OBJECT_DELETION = 0x0002;

//Association Type
constexpr std::uint16_t MTP_ASSOCIATION_TYPE_UNDEFINED = 0x0000; //Undefined
constexpr std::uint16_t MTP_ASSOCIATION_TYPE_GENERIC_FOLDER = 0x0001; //Unused by PTP; used by MTP to indicate type of folder


//MIGHT BE NEEDED
// Android extensions for direct file IO
// Same as GetPartialObject, but with 64 bit offset
#define MTP_OPERATION_GET_PARTIAL_OBJECT_64                 0x95C1
// Same as GetPartialObject64, but copying host to device
#define MTP_OPERATION_SEND_PARTIAL_OBJECT                   0x95C2
// Truncates file to 64 bit length
#define MTP_OPERATION_TRUNCATE_OBJECT                       0x95C3
// Must be called before using SendPartialObject and TruncateObject
#define MTP_OPERATION_BEGIN_EDIT_OBJECT                     0x95C4
// Called to commit changes made by SendPartialObject and TruncateObject
#define MTP_OPERATION_END_EDIT_OBJECT                       0x95C5

#endif //MTP_H
